name: dbt-cd

on:
  push:
    branches: [main]
    paths:
      - "dbt/**"

jobs:
  dbt-cd:
    name: dbt Run
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: dbt

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: pip install dbt-redshift

      - name: dbt Run
        env:
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: dbt run --profiles-dir .

      - name: dbt Test
        env:
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
        run: dbt test --profiles-dir .
